apiVersion: v2
name: dp-config-aws
version: "1.0.12"
appVersion: "1.0.0"
description: dp-config-aws is used to config CIC2 TIBCO Dataplane
type: application
home: https://github.com/tibco/cicinfra-integration
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
dependencies:
  - name: traefik
    version: 24.0.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "update traefik to 24.0.0"
