# name of chart
name: dp-otel-collectors
# label indicating which project this pipeline belongs to (Don't change)
partOf: TIBCO-Platform
# indicating which tools are used to generate this template (Don't change)
createdBy: generator

# this is for user app
collector1:
  enabled: true
  name: otel-tibco-user-app
  mode: "deployment"
  apmEndpoint: ""
  apmToken: ""
  esEndpoint: ""
  esUserName: ""
  esPassword: ""
  esLogIndex: ""
  esTraceIndex: ""
  prometheusEndpoint: ""
  prometheusToken: ""
  ports:
    fluentforward:
      enabled: true
      targetPort: 8006
      port: 8006
      protocol: TCP
    metrics:
      enabled: true
      targetPort: 8888
      port: 8888
      protocol: TCP
  config: ""

# this is for k8s events
k8sEventsCollector:
  enabled: true
  name: otel-tibco-k8s-event
  mode: "deployment"
  namespacesList: ""
  esEndpoint: ""
  esUserName: ""
  esPassword: ""
  esLogIndex: ""
  config: ""

# metrics-collector
metricscollector:
  enabled: true
  name: otel-metric-collector
  mode: "deployment"
  prometheusEndpoint: ""
  prometheusToken: ""
  jaegerGRPCEndpoint: ""
  jaegerThriftCompactEndpoint: ""
  jaegerThriftHttpEndpoint: ""
  zipkinEndpoint: ""
  ports:
    fluentforward:
      enabled: true
      targetPort: 8006
      port: 8006
      protocol: TCP
    metrics:
      enabled: true
      targetPort: 8888
      port: 8888
      protocol: TCP
  config: "" 

# tibco-otel-collector-services
tibotelcollectorsvc:
  enabled: true
  name: tibco-otel-collector
  mode: "deployment"
  esEndpoint: ""
  esUserName: ""
  esPassword: ""
  esLogIndex: ""
  esTraceIndex: ""
  config: ""

# tibco-service-collector-user-app
tibotelcollectoruserapp:
  enabled: true
  name: tibco-otel-collector-user-app
  mode: "deployment"
  namespacesList: ""
  apmEndpoint: ""
  apmToken: ""
  esEndpoint: ""
  esUserName: ""
  esPassword: ""
  esLogIndex: ""
  esTraceIndex: ""
  prometheusEndpoint: ""
  prometheusToken: ""
  ports:
    fluentforward:
      enabled: true
      targetPort: 8006
      port: 8006
      protocol: TCP
    metrics:
      enabled: true
      targetPort: 8888
      port: 8888
      protocol: TCP
  config: ""

# tibco-service-collector-finops
tibotelcollectorfinops:
  enabled: true
  name: tibco-otel-collector-finops
  mode: "deployment"
  apmEndpoint: ""
  apmToken: ""
  ports:
    metrics:
      enabled: true
      targetPort: 8888
      port: 8888
      protocol: TCP
  config: ""

tibotelcollectornops:
  enabled: true
  name: tibco-otel-collector-nops
  mode: "deployment"
  namespacesList: ""
  ports:
    fluentforward:
      enabled: true
      targetPort: 8006
      port: 8006
      protocol: TCP
    metrics:
      enabled: true
      targetPort: 8888
      port: 8888
      protocol: TCP
  config: ""