apiVersion: v1
name: distributed-lock-operator
version: 1.0.0
appVersion: "1.0.0"
description: TIBCO Platform Dataplane Infrastructre Core -- Distributed Lock operator
home: https://github.tibco.com/tibco/cicinfra-cic2-distributed-lock-operator.git
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
  - name: TIBCO CIC Compute Dev Team
    email: compute-dev@tibco.com 
