apiVersion: v2
appVersion: 1.0.243
dependencies:
- condition: tp-tibtunnel.enabled
  name: tp-tibtunnel
  repository: https://syan-tibco.github.io/tp-helm-charts
  version: 1.0.77
- condition: tp-provisioner-agent.enabled
  name: tp-provisioner-agent
  repository: https://syan-tibco.github.io/tp-helm-charts
  version: 1.0.189
- condition: haproxy-ingress.enabled
  name: haproxy-ingress
  repository: ""
  version: v0.14.0
- condition: config.enabled
  name: config
  repository: ""
  version: 1.0.0
description: A Helm chart for TIBCO Platform Data Plane Infrastructure
name: dp-core-infrastructure
type: application
version: 1.0.243
