apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-{{ .Release.Namespace }}{{- if not (eq .Values.revision "")}}-{{ .Values.revision }}{{- end }}-role
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-{{ .Release.Namespace }}{{- if not (eq .Values.revision "")}}-{{ .Values.revision }}{{- end }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "istio.controller.serviceAccountName" . }}
    namespace: {{ .Values.global.istioNamespace }}
