# Resources
# https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 200m
    memory: 300Mi

# no of replicas
replicaCount: "1"



image:
  registry: ""
  repository: stratosphere/tp-cp-proxy
  pullPolicy: IfNotPresent

# Kubectl and curl are required by the job responsible for creating. TODO: we should revisit docker-image(this one is 445 mb). bitnami/kubectl does not support curl.
clientCredentials:
  # intialAccessToken : Control Plane Authentication TODO: terminologies are not fixed yet, will revisit later.
  # this is used to generate client id and client secret.
  # Client Id and secret are used to generate time bound access token
  initialAccessToken: "test" #initial access token used to generate client credentials

nodeSelector:
  kubernetes.io/os: linux

affinity: {}

global:
  cp:
    dataplaneId: "abcd"
    subscriptionId: "sub1"
    controlPlaneUrl: "https://account.local.cic2.pro"
    serviceAccount: ""
    containerRegistry:
      url: reldocker.tibco.com
